config/routes.rb
Ecommerce::Application.routes.draw do
    
    devise_for :users
    resources :products 
    
    
    resources :carts do
      post 'remove_item' => "carts#remove_item"
      resources :charges
    end

    root 'products#index'
    

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_and_belongs_to_many :products
	
	def count
		products.count
	end

	def total
		prices_array = products.map {|x| x.price.to_i}
		total = prices_array.inject {|sum,n| sum + n}

		# return prices
		# products.inject {|total, product| total.price.to_i + product.price.to_i}
	end
end

app/models/order.rb
class Order < ActiveRecord::Base

  after_create :send_confirmation_email

  def send_confirmation_email
    OrderNotifier.confirmation_email(number_of_items).deliver!
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  	
  	has_attached_file :product_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing.jpg"

  	has_and_belongs_to_many :carts

    monetize :price
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :create_empty_cart
  before_filter :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_cart



  def create_empty_cart
  	session[:cart_id] ||= Cart.create.id  
  end	

  def current_cart
  	Cart.find session[:cart_id]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def update
      product = Product.find params[:cart][:product_id]
  		current_cart.products << product

  		redirect_to product_path(product)
  end

  def remove_item
      render :text => params.inspect
      # product = Product.find params[:product_id]
      # current_cart.products.delete(product)
      # flash.notice = "Product #{product.name} removed from cart"
      # render 'show'
	end

	def show
		@cart = current_cart.products
	end
	
  def destroy
    # flash[:notice] = "Product: #{@product.name} removed from cart"
    redirect_to '/'
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = Cart.find params[:cart_id]
  end

   # def create
   #  # Amount in cents
   #  @amount = 500

   #  customer = Stripe::Customer.create(
   #    :email => 'example@stripe.com',
   #    :card  => params[:stripeToken]
   #  )

   #  charge = Stripe::Charge.create(
   #    :customer    => customer.id,
   #    :amount      => @amount,
   #    :description => 'Rails Stripe customer',
   #    :currency    => 'usd'
   #  )



   #  rescue Stripe::CardError => e
   #  flash[:error] = e.message
   #  redirect_to charges_path
  end

  def create
    @cart = params[]
    @amount = cart.total

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )



    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_t

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def create
		@product = Product.new product_params
		if @product.save
			redirect_to product_path(@product)
		else
			render 'new'
		end
	end	

	def new
		@product = Product.new
	end

	def product_params
		params.require(:product).permit :name, :description, :price, :product_image
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update product_params
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		Product.destroy(@product)
		flash[:notice] = "Product: #{@product.name} deleted"
		redirect_to '/'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.haml
%ul{class: 'cart_details'}
  - @cart.each do |product|
    %li
      = product.name
      = humanized_money_with_symbol(product.price)
      = image_tag product.product_image.url(:thumb)
      = form_tag cart_remove_item_path(current_cart) do
        = hidden_field_tag :product_id, product.id
        = submit_tag 'Remove from cart'

.cart_total
Total: 
= current_cart.total
.links
  = link_to "Continue Shopping", root_path
  = link_to "Checkout", new_cart_charge_path(current_cart)

app/views/charges/charges.html.erb
<html>
<head>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= number_to_currency current_cart.total, unit: '£' %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag cart_charges_path do %>
  <article>
      <label class="amount">
        <span>Amount: <%= number_to_currency current_cart.total, unit: '£' %> </span>
      </label>
  </article>

<script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= number_to_currency current_cart.total * 100, unit: '£' %>></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ecommerce" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Dave's Bike Store</a>
        
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
          <% if current_user %>
              <li class="active"><%= link_to "Sign out", destroy_user_session_path %></li>
          <% else %>
              <li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
              <li class="active"><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
              <li class="active"><%= link_to "My Cart", cart_path(current_cart) %></li> 
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <p class="notice"><%= flash[:notice] %></p>
          <p class="alert"><%= alert %></p>
          <div class='item_count'>
            <%= pluralize current_cart.count, 'item' %>
          </div>

          <div class='cart_total'>Total:
            <%= current_cart.total %>
          </div>
          
            <%= yield %>
          
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/order_notifier/confirmation_email.html.erb
<p>Helloooooo</p>

<p>Thanks for your order. You ordered <%= pluralize @number_of_items, 'item' %></p>

<p>They'll be there soon.<p>

app/views/products/edit.html.haml
= form_for @product, :url => product_path(@product), :html => { :multipart => true } do |p|
	= p.label :name 
	= p.text_field :name
	= p.label :description 
	= p.text_area :description
	= humanized_money_with_symbol p.label :price
	= p.text_field :price
	= p.file_field :product_image
	= p.submit 'Update'

app/views/products/index.html.haml
%p
- @products.each do |product|
  = link_to product.name, product_path(product)
  = image_tag product.product_image.url(:thumb)
  = humanized_money_with_symbol product.price

app/views/products/new.html.haml
%p
= form_for @product, :url => products_path, :html => { :multipart => true } do |f|
	= f.label :name 
	= f.text_field :name
	= f.label :description 
	= f.text_area :description
	= f.label :price
	= f.text_field :price
	= f.file_field :product_image
	= f.submit 'Add New Product'

app/views/products/show.html.haml
= @product.name
= @product.description
= humanized_money_with_symbol @product.price
= image_tag @product.product_image.url(:medium)

= form_for current_cart do |f|
  = f.hidden_field :product_id, value: @product.id
  = f.submit 'Add to Cart'

- if current_user
  = link_to 'Edit', edit_product_path(@product)
  = link_to 'Delete', product_path(@product), method: :delete

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>